# conf/llm/default.yaml - Default LLM configuration
provider: "anthropic" # openai, anthropic, qwen
model_name: "claude-3-7-sonnet-20250219"
async_client: false
temperature: 0.3
top_p: 1.0
min_p: 0.0
top_k: -1
max_tokens: 4096
max_context_length: 200000
api_key: ""
base_url: https://api.anthropic.com
repetition_penalty: 1.0
